# Generated by Django 4.1 on 2022-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
